url: http://berkasansor.com/
baseurl: ""

# Site settings
title: Berk Asansör | İstanbul Modern Asansör Çözümleri
email: berkasansor@hotmail.com
description: "Berk Asansör, İstanbul'da asansör bakım, arıza, modernizasyon ve montaj hizmetleri sunmaktadır. 30 yıllık tecrübemizle kaliteli ve güvenli asansör çözümleri."
keywords: "asansör bakım, asansör arıza, asansör modernizasyon, istanbul asansör firması, berk asansör, asansör montaj"
author: "Berk Asansör"

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed

# Team names, titles and social links
people:
- name: Berk Asansör Ekibi
  pic: 1
  position: Teknik Uzman
  social:
    - title: facebook
      url: https://www.facebook.com/Berk-Asans%C3%B6r-185447965283429/

# Social networks usernames
social:
  - title: twitter
    url: http://twitter.com/berkasansor
  - title: facebook
    url: https://www.facebook.com/Berk-Asans%C3%B6r-185447965283429/

# Postal address
address: Namık Kemal Mah. Yunus Emre Cadddesi Bayrak Sokak Mevlana Apartmanı 3 / Dükkan 2 Ümraniye İstanbul
phone: (216) 328 80 26
gsm: (0532) 332 04 26
fax: (216) 328 92 96

# Build settings
markdown: kramdown
permalink: /blog/:title/

collections:
  urunler:
    output: true
    permalink: /urunler/:path/